.Dd $Mdocdate: September 11 2022 $
.Dt TRUE 1
.Os
.Sh NAME
.Nm true
.Nd return true value
.Sh SYNOPSIS
.Nm true
.Sh DESCRIPTION
The
.Nm
utility always returns with exit code zero.
.Sh EXIT STATUS
The
.Nm
utility always returns with exit code zero.
.Sh SEE ALSO
.Xr false 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification
.Sh AUTHORS
The
.Nm
utility was written by
.An Emil Engler Aq Mt me@emilengler.com .
